name: Build Aseprite for Windows

on:
  workflow_dispatch: # 允许手动触发构建

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: 检出 Aseprite 源码
        uses: actions/checkout@v4
        with:
          repository: aseprite/aseprite
          submodules: recursive

      - name: 安装 vcpkg 和依赖项
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat
          .\vcpkg install freetype giflib libpng jpeg-turbo jsoncpp curl
        shell: cmd

      - name: 获取并编译 Skia
        run: |
          git clone -b aseprite-m81 https://github.com/aseprite/skia.git
          cd skia
          ./tools/git-sync-deps
          mkdir build && cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
          ninja
        shell: bash

      - name: 编译 Aseprite
        run: |
          mkdir build && cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DSKIA_DIR=../skia -DSKIA_LIBRARY_DIR=../skia/build/out/Release \
            -DSKIA_LIBRARY=../skia/build/out/Release/skia.lib -DWITH_SKIA=ON ..
          ninja aseprite
        shell: bash

      - name: 打包可执行文件
        run: |
          mkdir artifact
          copy build\bin\aseprite.exe artifact\
          tar -czf aseprite-windows.tar.gz -C artifact .
        shell: cmd

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: aseprite-build-windows
          path: aseprite-windows.tar.gz
